[build]
  command = "npm run build"
  publish = "build"

[dev]
  command = "npm start"
  port = 3000

[build.environment]
  CI = "false"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
